micronaut:
  application:
    name: micronautguide
netty:
  default:
    allocator:
      max-order: 3


jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false


